### ISSUE TITLE
GUI display of charcoal use per recipe does not work

### ISSUE THREAD

**Issue by wingzero54** [CivMC/FactoryMod#2]
Charcoal cost is tied in the config to factory runtime (1 charcoal per second of runtime) so the display for charcoal cost does not work and is always 0

**Comment by Diet-Cola** [comment]
The cause of this is due to a missing config flag

```
  make_diamond_sword:
    production_time: 4s
    name: Make Diamond Sword
    type: PRODUCTION
    input:
      diamond:
        material: DIAMOND
        amount: 10
    output:
      diamond_sword:
        material: DIAMOND_SWORD
        amount: 15
```

is a typical civclassic config example, however when we add the `fuel_consumption_intervall` line, as below:

```
  make_diamond_sword:
    production_time: 4s
    fuel_consumption_intervall: 1s
    name: Make Diamond Sword
    type: PRODUCTION
    input:
      diamond:
        material: DIAMOND
        amount: 10
    output:
      diamond_sword:
        material: DIAMOND_SWORD
        amount: 15
```

We get: 
![image](https://user-images.githubusercontent.com/12645603/157995698-ffc9b1ee-ecaa-417e-b795-3fdeea71372c.png)
